changed new form to a different page route
jyh106/GiveAwayWebsite pull request #13
Opened 2018-12-28 04:24 UTC by jyh106

2019-01-08 19:50 UTC, jyh106 commented
ptal @alixander

2019-01-09 06:00 UTC, alixander requested changes
Minor comments. LGTM after!

2019-01-09 06:00 UTC, alixander commented on src/NewForm/NewForm.js
> +import React, { Component } from 'react';
You should have the name of the file reflect the component

2019-01-09 06:00 UTC, alixander commented on src/NewForm/NewForm.js
> +    onChangeInput(type, answer){
`onInputChange`?

2019-01-09 06:00 UTC, alixander commented on src/NewForm/NewForm.js
> +            index++;
You should use a traditional `for loop` instead of a `for each` loop if you're doing this. E.g., `for (let i = 0; i < this.state.images.length; i++)`

2019-01-09 06:00 UTC, alixander commented on src/NewForm/NewForm.js
> +    createNewImagesList(e) {
Not clear what this is doing. This is where comments should help. I think if you were to review this piece of code again in a month, you'd be confused yourself as well.

2019-01-09 06:00 UTC, alixander commented on src/NewForm/NewForm.js
> +                <button className={`newForm_buttons newFormButton_submit ${(this.isSubmitButtonEnable()) ? "submit_enable" : "submit_disable"}`}
nit. This looks kind of ugly inline in JSX. I'd take it out into a separate variable, e.g. `buttonClassName = ...`

2019-01-09 06:16 UTC, merged